name = "SHades"
uuid = "44f0f368-06fe-4e52-966c-7b0a715b31a3"
version = "0.1.0"

[deps]
Cairo = "159f3aea-2a34-519c-b102-8c37f9878175"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Gtk = "4c0ca9eb-093a-5379-98c5-f87ac0bbbf44"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
